development:
  adapter: sqlite3
  database: db/dev-patients.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test-patients.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/prod-patients.sqlite3
  pool: 5
  timeout: 5000
